import { Certification } from "@/lib/types";

export const certifications: Certification[] = [
  {
    title: "Claude 101",
    issuer: "Anthropic",
    href: "https://verify.skilljar.com/c/42pm34m2ocq5",
    issuedDate: "Apr 2026",
    image: "/logos/logo_claude101.png",
    skills: ["LLMs", "Prompt engineering"],
  },
  {
    title: "AI Agent Fundamentals",
    issuer: "Databricks",
    href: "https://credentials.databricks.com/1475b7d0-ef35-4ef4-850c-583cb67fdf00#acc.sQy57wMi",
    issuedDate: "Mar 2026",
    image: "/logos/logo_databricks.png",
    skills: ["LLMs", "Agentic AI"],
  },
  {
    title: "AI Agents Fundamentals",
    issuer: "Hugging Face",
    href: "https://huggingface.co/datasets/agents-course/certificates/resolve/main/certificates/sergiov2000/2025-02-11.png",
    issuedDate: "Feb 2025",
    credentialId: "sergiov2000",
    image: "/logos/logo_huggingface.png",
    skills: ["LLMs", "Agentic AI"],
  },
  {
    title: "International Student",
    issuer: "Università degli Studi di Milano-Bicocca",
    href: "https://bestr.it/award/show/0Z3jzLeGQHmLcc74NB9Gvw",
    issuedDate: "Dec 2024",
    image: "/logos/logo_unimib.png",
    skills: ["International", "Erasmus"],
  },
  {
    title: "Proficiency in KNIME Software for Collaboration and Productionization",
    issuer: "KNIME",
    href: "https://www.credly.com/badges/873d4e4b-5b6d-47e9-9a03-e45751fb4bed/linked_in_profile",
    issuedDate: "Dec 2024",
    expiryDate: "Dec 2026",
    image: "/logos/logo_knime.png",
    skills: ["Data mining", "Machine learning"],
  },
  {
    title: "Advanced Proficiency in KNIME Analytics Platform",
    issuer: "KNIME",
    href: "https://www.credly.com/badges/4d873957-3dfa-49c9-a283-97531be8d093/linked_in_profile",
    issuedDate: "Oct 2024",
    expiryDate: "Oct 2026",
    image: "/logos/logo_knime.png",
    skills: ["Data mining", "Machine learning"],
  },
  {
    title: "Basic Proficiency in KNIME Analytics Platform",
    issuer: "KNIME",
    href: "https://www.credly.com/badges/e70e596d-3e89-47b6-ac86-7ea8e4cb33e3/linked_in_profile",
    issuedDate: "Oct 2024",
    image: "/logos/logo_knime.png",
    skills: ["Data mining", "Machine learning"],
  },
  {
    title: "English C1 BBetween",
    issuer: "Universita degli Studi di Milano-Bicocca",
    href: "https://bestr.it/award/show/m9VSIr-7Q3qoNGPXuKUJbw",
    issuedDate: "Sep 2024",
    credentialId: "m9VSIr-7Q3qoNGPXuKUJbw",
    image: "/logos/logo_unimib.png",
    skills: ["English", "CEFR C1"],
  },
  {
    title: '1st place in the "Machine Learning Challenge" - Spring 2024',
    issuer: "KNIME",
    href: "https://openbadges.bestr.it/public/assertions/m9VSlr-7Q3qoNGPXuKJJbw",
    issuedDate: "May 2024",
    image: "/logos/logo_knime.png",
    skills: ["Data mining", "Machine learning"],
  },
];
